<a href="https://colab.research.google.com/github/dharshdk/ML/blob/main/NN_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

In [3]:
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [4]:
y=np.array([[1],[0],[1]])

In [10]:
y

array([[1],
       [0],
       [1]])

In [11]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [12]:
def derivative_sigmoid(x):
  return x*(1-x)

In [13]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [16]:
input_neurons

4

In [14]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [15]:
wh

array([[0.67809419, 0.22680685, 0.21996925],
       [0.29738617, 0.31081472, 0.13843189],
       [0.40456111, 0.29056317, 0.54045456],
       [0.22601004, 0.12146106, 0.09780139]])

In [17]:
for i in range(epoch):
  #forward
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)
  #backward
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr

In [18]:

output

array([[0.95675475],
       [0.06806849],
       [0.97031198]])