<a href="https://colab.research.google.com/github/dharshdk/ML/blob/main/numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=[]
a.append(5)
print(a)

[5]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a[1,0]=9
a

array([[1, 2, 3],
       [9, 5, 6]])

In [ ]:
b=[1,6,2,7,9]
b.append(9)
b.insert(3,5)
print(b)
print(b[1:4])
b.extend(a)
print(b)

[1, 6, 2, 5, 7, 9, 9]
[6, 2, 5]
[1, 6, 2, 5, 7, 9, 9, 5, 2, 1, 2, 2, 5, 5, 5]


In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a.shape)
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
c=np.arange(3,10)#puts the numbers between given intervals
print(c)
print(type(a))#provides the model

(3,)
(2, 3)
[3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
np.random.random(3)

array([0.57116062, 0.2248007 , 0.84242248])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones((3,2))

In [ ]:
np.zeros((3,2))

In [ ]:
np.random.random((3,2))

array([[0.9949185 , 0.06464445],
       [0.48627158, 0.35115782],
       [0.36261412, 0.95637025]])

In [ ]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
c=np.full((2,2),7)#create a constant array
print(c)

[[7 7]
 [7 7]]


In [ ]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.random.random((4,3,2))

array([[[0.36729284, 0.804383  ],
        [0.65296278, 0.48696344],
        [0.52215307, 0.16843229]],

       [[0.263712  , 0.06186634],
        [0.53170377, 0.75165833],
        [0.78301094, 0.04201553]],

       [[0.11140596, 0.76596983],
        [0.94177453, 0.95366655],
        [0.49906823, 0.52778745]],

       [[0.31769218, 0.85931581],
        [0.88888223, 0.39753063],
        [0.58362808, 0.06866961]]])

In [ ]:
f=np.arange(10,50,5)#create an array of values starting at 10 in increment of 5
print(f)

[10 15 20 25 30 35 40 45]


In [ ]:
g=np.linspace(0.,1.,num=5)#splits the start and lst number with even num splitups
print(g)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
h=np.array([1,2,3],dtype=np.float64)
print(h)
i=np.array([1,2,3],dtype=np.complex)
print(i)

[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


<ipython-input-33-a14d911f60fd>:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  i=np.array([1,2,3],dtype=np.complex)


In [ ]:
a=[1,2,3]
print(a[0])
k=np.array([[1,2,3],[3,4,7],[4,5,6]])
print(k)
print(k[0,1])
print(k[1:3])
print(k[0:2,0])

1
[[1 2 3]
 [3 4 7]
 [4 5 6]]
2
[[3 4 7]
 [4 5 6]]
[1 3]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:3,1:3]
b
c=a[1:3,2:4]
c

array([[ 7,  8],
       [11, 12]])

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[1,:]#rank 1 view of second rowof a
c=a[1:3,:]#rank2 view of the second row of a
d=a[[1],:]#rank2 view of the second row of a
print(b,b.shape)
print(c,c.shape)
print(d,d.shape)

[5 6 7 8] (4,)
[[ 5  6  7  8]
 [ 9 10 11 12]] (2, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[1,6,8,9],[4,7,2,4],[9,3,7,1]])
a

array([[1, 2, 3, 4],
       [1, 6, 8, 9],
       [4, 7, 2, 4],
       [9, 3, 7, 1]])

In [ ]:
b=np.array([0,2,0,1])
print(a[np.arange(4),b])

[1 8 4 3]


In [ ]:
a[np.arange(4),b] +=10
print(a)

[[11  2  3  4]
 [ 1  6 18  9]
 [14  7  2  4]
 [ 9 13  7  1]]


In [ ]:
 a = np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [ ]:
a[bool_idx]

array([3, 4, 5, 6])

In [ ]:
a[a>2]

array([3, 4, 5, 6])

In [ ]:
a=np.array([1,8,9,-3,2,4,7,9])#every function gives the index values of the elements
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a>5)[0])
print(np.where(a>=a[np.argmax(a)])[0])

2
3
[3 0 4 5 6 1 2 7]
[7 2 1 6 5 4 0 3]
[1 2 6 7]
[2 7]


In [ ]:
a=[0]
a=np.append(a,[1,2,3,4])
print(a)

[0 1 2 3 4]


In [ ]:
a=np.delete(a,[2,3])
print(a)

[0 1 4]


In [ ]:
a=np.array([[3,2,1],[9,8,7],[6,5,4]])
print(a)

a=np.sort(a,axis=0,kind='quicksort')
print(a)

[[3 2 1]
 [9 8 7]
 [6 5 4]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
a=np.array([[3,2,1],[9,8,7],[6,5,4]])
print(a)

a=np.sort(a,axis=1,kind='quicksort')
print(a)

[[3 2 1]
 [9 8 7]
 [6 5 4]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [ ]:
%%time
x=np.sum(a)

CPU times: user 48 µs, sys: 0 ns, total: 48 µs
Wall time: 49.8 µs


In [ ]:
w=np.array([[1],[2],[3]])#it gives uncessary brackets
print(w)
w.shape

[[1]
 [2]
 [3]]


(3, 1)

In [ ]:
y=w.squeeze()#removes uncessary brackets
print(y)
y.shape

[1 2 3]


(3,)

In [ ]:
y.reshape(-1,1)#also given as y.reshape(-1,)
print(y)
y.shape

[1 2 3]


(3,)

In [ ]:
x=np.array([[1,2],[3,4],[5,6]])#transpose of the given matrix
print(x)
print(x.T)


[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [ ]:
#BROADCASTING nothing but extending and add
a=np.array([1,2,3])
b=np.array([[4],[5],[6]])
c=a+b
a

array([1, 2, 3])

In [ ]:
b

array([[4],
       [5],
       [6]])

In [ ]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])